#!/usr/bin/env python3
"""
Render the TLEMCENYA site: one template, three locales, static HTML out.

    python3 build.py

Writes index.html (fr), en/index.html, ar/index.html. No runtime build step:
the generated files are plain HTML and ship as-is.
"""
from __future__ import annotations

import base64
import hashlib
import html
import json
import os
import re
from urllib.parse import quote, urlsplit
import pathlib

ROOT = pathlib.Path(__file__).parent
LOCALES = ["fr", "en", "ar"]
BRAND_DEFAULT = "TLEMCENYA"

# The public origin, e.g. "https://tlemcenya.dz". Empty until the domain is
# registered: canonical links, hreflang, og:image and sitemap.xml all need
# absolute URLs, and a URL pointing at a domain you do not own is worse than
# no URL at all. Set it once and rebuild:  SITE_URL=https://… python3 build.py
SITE_URL = os.environ.get("SITE_URL", "").rstrip("/")

# Every inline script and inline event handler on the site, in one place, so
# the Content-Security-Policy hashes written to _headers cannot drift away
# from what the pages actually contain.
JS_NOJS = "document.documentElement.classList.remove('no-js')"
JS_FONT_SWAP = "this.media='all'"
JS_IMG_FALLBACK = "this.closest('picture')?.remove?.()||this.remove()"

# ---------------------------------------------------------------- helpers

# A range is "<number> <dash> <number>" with whitespace around the dash,
# so a hyphenated code such as TLM-25-114 is never matched.
RANGE = re.compile(r"\d[\d.,\u202f]*\s[–—-]\s\d[\d.,]*\s?[%\u066a]?")
LRI, PDI = "\u2066", "\u2069"


def e(s: object) -> str:
    return html.escape(str(s), quote=True)


def num(s: object, lang: str) -> str:
    """Escape, and in RTL pin numeric ranges to LTR.

    Arabic is an RTL paragraph, and digits are bidi-weak: without an
    explicit isolate the browser renders "18 - 22%" as "22% - 18".
    """
    if lang != "ar":
        return e(s)
    # Unicode isolates rather than markup: these survive inside <option>,
    # attribute values and plain text, where a <span> cannot go.
    return e(RANGE.sub(lambda m: LRI + m.group(0) + PDI, str(s)))


# Aspect ratios are collected as they are emitted and written out as real
# CSS classes, so no page carries a style="" attribute. That keeps the
# Content-Security-Policy free of 'unsafe-inline' / 'unsafe-hashes' for
# styles: an attacker who finds an injection point still cannot restyle the
# page into a convincing fake form.
RATIOS: set[str] = set()


def ratio_class(r: str) -> str:
    r = " ".join(str(r).split())
    RATIOS.add(r)
    return "ar-" + re.sub(r"[^0-9a-z]+", "-", r.lower()).strip("-")


def write_ratio_css() -> None:
    lines = ["/* Generated by build.py — do not edit. */", "@layer components {"]
    for r in sorted(RATIOS):
        lines.append(f"  .{ratio_class(r)} {{ aspect-ratio: {r}; }}")
    lines.append("}")
    (ROOT / "src" / "_ratios.css").write_text("\n".join(lines) + "\n", "utf-8")


def icon(name: str, size: int = 20) -> str:
    """Inline stroke icons. One family, one stroke width (1.6), no emoji."""
    paths = {
        "download": '<path d="M12 3v12m0 0 4.5-4.5M12 15l-4.5-4.5M4 19.5h16"/>',
        "alert": '<circle cx="12" cy="12" r="9"/><path d="M12 7.5v5.5M12 16.5h.01"/>',
        "check": '<path d="M4.5 12.5 9 17 19.5 6.5"/>',
        "menu": '<path d="M4 7h16M4 12h16M4 17h16"/>',
        "close": '<path d="M6 6l12 12M18 6 6 18"/>',
        "seal": '<path d="M12 3.2 14.3 5l2.8-.3 1 2.6 2.4 1.5-.8 2.7.8 2.7-2.4 1.5-1 2.6-2.8-.3L12 20.8 9.7 19l-2.8.3-1-2.6L3.5 15.2l.8-2.7-.8-2.7 2.4-1.5 1-2.6 2.8.3z"/><path d="M9 12.2l2.1 2.1L15.3 10"/>',
        "drop": '<path d="M12 3.5c3.2 4 5.2 6.6 5.2 9.2a5.2 5.2 0 0 1-10.4 0c0-2.6 2-5.2 5.2-9.2z"/>',
        # WhatsApp is a filled mark, not a stroked one: drawn at 1.6 stroke
        # weight beside our own icons it reads as a different family.
        "whatsapp": '<path fill="currentColor" stroke="none" d="M12.04 2C6.58 2 2.13 6.45 2.13 11.91c0 1.75.46 3.45 1.32 4.95L2 22l5.25-1.38a9.9 9.9 0 0 0 4.79 1.22h.01c5.46 0 9.9-4.45 9.91-9.91a9.85 9.85 0 0 0-2.9-7.01A9.82 9.82 0 0 0 12.04 2zm0 1.82c2.17 0 4.2.85 5.74 2.38a8.06 8.06 0 0 1 2.37 5.73c0 4.47-3.64 8.1-8.11 8.1a8.2 8.2 0 0 1-4.18-1.14l-.3-.18-3.11.82.83-3.04-.2-.31a8.05 8.05 0 0 1-1.24-4.32c0-4.47 3.64-8.1 8.2-8.04zm-3.2 4.03c-.16 0-.42.06-.64.3-.22.24-.85.83-.85 2.02s.87 2.34.99 2.5c.12.16 1.7 2.6 4.13 3.65.58.25 1.03.4 1.38.51.58.19 1.11.16 1.53.1.47-.07 1.44-.59 1.64-1.16.2-.57.2-1.05.14-1.16-.06-.1-.22-.16-.47-.28-.24-.12-1.44-.71-1.66-.79-.22-.08-.39-.12-.55.12-.16.24-.63.79-.77.95-.14.16-.28.18-.53.06-.24-.12-1.03-.38-1.96-1.21-.72-.65-1.21-1.44-1.35-1.68-.14-.25-.02-.38.1-.5.11-.11.24-.28.37-.43.12-.15.16-.25.24-.41.08-.17.04-.31-.02-.43-.06-.12-.55-1.32-.75-1.81-.2-.47-.4-.41-.55-.42h-.47z"/>',
    }
    return (
        f'<svg viewBox="0 0 24 24" width="{size}" height="{size}" fill="none" '
        f'stroke="currentColor" stroke-width="1.6" stroke-linecap="round" '
        f'stroke-linejoin="round" aria-hidden="true" focusable="false">{paths[name]}</svg>'
    )


def datagrid(items: list[dict], cols: str, lang: str = "fr") -> str:
    cells = "".join(
        f'<div><dt>{e(i["label"])}</dt><dd class="tnum">{num(i["value"], lang)}</dd></div>'
        for i in items
    )
    return f'<dl class="datagrid {cols}">{cells}</dl>'


def table(head: list[str], rows: list[list[str]], caption: str, lang: str = "fr") -> str:
    th = "".join(f"<th scope=\"col\">{e(h)}</th>" for h in head)
    body = ""
    for r in rows:
        cells = f'<th scope="row">{num(r[0], lang)}</th>' + "".join(
            f'<td>{num(c, lang)}</td>' for c in r[1:]
        )
        body += f"<tr>{cells}</tr>"
    return (
        f'<div class="scroll-x"><table class="spec"><caption>{e(caption)}</caption>'
        f"<thead><tr>{th}</tr></thead><tbody>{body}</tbody></table></div>"
    )

# ---------------------------------------------------------------- sections

def picture(src: str, alt: str, w: int, h: int, sizes: str) -> str:
    """An <img>, upgraded to <picture> only for formats that exist on disk.

    A <source> is chosen on format support, not on the file being there:
    listing an AVIF that 404s makes the whole picture fail, exactly as a
    missing webm once killed the hero video.
    """
    local = ROOT / src.replace("../", "")
    alts = ""
    for ext, mime in (("avif", "image/avif"), ("webp", "image/webp")):
        cand = local.with_suffix("." + ext)
        if cand.exists():
            alts += f'<source type="{mime}" srcset="{e(src.rsplit(".", 1)[0])}.{ext}" sizes="{e(sizes)}">'
    img = (
        f'<img src="{e(src)}" alt="{e(alt)}" width="{w}" height="{h}" sizes="{e(sizes)}" '
        f'loading="lazy" decoding="async" onerror="{e(JS_IMG_FALLBACK)}">'
    )
    return f"<picture>{alts}{img}</picture>" if alts else img


def head_tag(c: dict, assets: str, alts: list[dict]) -> str:
    m = c["meta"]
    base = SITE_URL
    page_url = f"{base}/{c['path']}" if base else "/" + c["path"]
    hreflang = "".join(
        f'<link rel="alternate" hreflang="{a["lang"]}" '
        f'href="{(base + "/" + a["path"]) if base else "/" + a["path"]}">'
        for a in alts
    )
    # og:image must be absolute — a relative one is silently dropped by every
    # scraper — so it appears only once the domain is known.
    og_image = (f'<meta property="og:image" content="{base}/assets/video/hero-poster.jpg">'
                f'<meta property="og:image:width" content="1920">'
                f'<meta property="og:image:height" content="1080">'
                f'<meta property="og:image:alt" content="{e(m["title"])}">'
                f'<meta name="twitter:card" content="summary_large_image">'
                if base else '<meta name="twitter:card" content="summary">')
    return f"""<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{e(m["title"])}</title>
<meta name="description" content="{e(m["description"])}">
<meta name="theme-color" content="#151a10">
<meta property="og:type" content="website">
<meta property="og:title" content="{e(m["title"])}">
<meta property="og:description" content="{e(m["description"])}">
<meta property="og:locale" content="{e(m["og_locale"])}">
<meta property="og:site_name" content="{e(c.get("brand", BRAND_DEFAULT))}">
<meta property="og:url" content="{e(page_url)}">
{og_image}
<link rel="canonical" href="{e(page_url)}">
{hreflang}<link rel="alternate" hreflang="x-default" href="{e(base + "/" if base else "/")}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" media="print" onload="{e(JS_FONT_SWAP)}"
      href="https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght,SOFT,WONK@9..144,300..700,0..100,0..1&family=Geist:wght@300..700&family=IBM+Plex+Sans+Arabic:wght@300;400;600&family=Reem+Kufi:wght@400..700&display=swap">
<noscript><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght,SOFT,WONK@9..144,300..700,0..100,0..1&family=Geist:wght@300..700&family=IBM+Plex+Sans+Arabic:wght@300;400;600&family=Reem+Kufi:wght@400..700&display=swap"></noscript>
<link rel="icon" href="{assets}img/favicon.svg" type="image/svg+xml">
<link rel="stylesheet" href="{assets}css/site.css">"""


def header(c: dict, assets: str, alts: list[dict]) -> str:
    links = "".join(
        f'<li><a class="navlink" href="{e(l["href"])}">{e(l["label"])}</a></li>' for l in c["nav"]
    )
    langs = "".join(
        f'<li><a href="/{a["path"]}" lang="{a["lang"]}" hreflang="{a["lang"]}"'
        + (' aria-current="true"' if a["lang"] == c["lang"] else "")
        + f'>{e(a["label"])}</a></li>'
        for a in alts
    )
    brand = e(c.get("brand", BRAND_DEFAULT))
    return f"""<a class="skip" href="#main">{e(c["skip"])}</a>
<header class="site-head on-dark" data-head>
  <div class="shell head-row">
    <a class="brand display" href="/{c["path"]}">{brand}</a>
    <button class="nav-toggle btn btn-quiet" type="button" data-nav-toggle
            aria-expanded="false" aria-controls="nav-panel"
            data-label-close="{e(c["nav_menu_close"])}">
      <span data-nav-label>{e(c["nav_menu_open"])}</span>
      <span data-nav-icon>{icon("menu")}</span>
    </button>
    <div class="nav-panel" id="nav-panel" data-nav-panel>
      <nav aria-label="{e(c["nav"][0]["label"])}">
        <ul class="navlist">{links}</ul>
      </nav>
      <nav class="langnav" aria-label="{e(c["footer"]["lang_label"])}">
        <ul>{langs}</ul>
      </nav>
      <a class="btn btn-primary head-cta" href="#{e(c["rfq"]["id"])}">{e(c["nav_cta"])}</a>
    </div>
  </div>
</header>"""


def hero(c: dict) -> str:
    h = c["hero"]
    lines = "".join(f"<span>{e(l)}</span>" for l in h["title_lines"])

    # Optional. data-src, not src: nothing is fetched until site.js decides
    # the viewport, the connection and the motion preference all allow it.
    v = h.get("video")
    video = ""
    if v and v.get("file"):
        webm = ""
        if v.get("webm") and (ROOT / v["webm"].lstrip("./").replace("../", "")).exists():
            webm = f'<source data-src="{e(v["webm"])}" type="video/webm">' 
        video = (
            f'<video class="hero-video" data-hero-video aria-hidden="true" tabindex="-1" '
            f'muted loop playsinline preload="none" poster="{e(v.get("poster", ""))}">'
            f'{webm}<source data-src="{e(v["file"])}" type="video/mp4"></video>'
        )

    return f"""<section class="hero on-dark grain" data-oil>
  <div class="oil-field" aria-hidden="true"><span></span><span></span><span></span><span></span></div>
  {video}
  <div class="shell hero-inner">
    <h1 class="display hero-title">{lines}</h1>
    <p class="hero-lede measure">{e(h["lede"])}</p>
    <div class="hero-actions">
      <a class="btn btn-primary" href="#{e(c["rfq"]["id"])}">{e(h["cta_primary"])}</a>
      <a class="btn btn-quiet" href="#{e(c["specs"]["id"])}">{e(h["cta_secondary"])}</a>
    </div>
    {datagrid(h["data"], "hero-data", c["lang"])}
  </div>
</section>"""


def variety(c: dict) -> str:
    v = c["variety"]
    s = v["slot"]
    body = "".join(f'<p class="measure">{e(p)}</p>' for p in v["body"])
    return f"""<section class="band band-stone" id="{e(v["id"])}">
  <div class="shell split">
    <div class="split-text reveal">
      <h2 class="display sec-title">{e(v["title"])}</h2>
      {body}
      {datagrid(v["facts"], "facts-grid", c["lang"])}
    </div>
    <figure class="split-media reveal">
      <div class="slot {ratio_class(s["ratio"])}">
        {picture(s["file"], s["alt"], 900, 1125, "(min-width: 56rem) 34vw, 92vw")}
      </div>
      <figcaption class="media-note">{e(s["caption"])}</figcaption>
    </figure>
  </div>
</section>"""


def products(c: dict) -> str:
    p = c["products"]
    sl = p["slot"]
    rows = ""
    for it in p["items"]:
        price = it.get("price", "").strip()
        # No invented prices: an empty field renders as a link to the
        # quotation form, which is how B2B export pricing actually works.
        value = (f'<span class="tnum">{e(price)}</span>' if price
                 else f'<a href="#{e(c["rfq"]["id"])}">{e(p["price_pending"])}</a>')
        rows += f"""<li class="product reveal">
      <p class="product-head"><span class="product-name tnum">{e(it["size"])}</span>
        <span class="product-size">{e(it["material"])}</span></p>
      <p class="product-body">{e(it["body"])}</p>
      <p class="product-price"><span>{e(p["price_label"])}</span> {value}</p>
    </li>"""
    return f"""<section class="band band-paper" id="{e(p["id"])}">
  <div class="shell split">
    <div class="split-text">
      <div class="sec-head reveal">
        <h2 class="display sec-title">{e(p["title"])}</h2>
        <p class="measure sec-lede">{e(p["lede"])}</p>
      </div>
      <ul class="products">{rows}</ul>
      <p class="price-note reveal">{e(p["price_note"])}</p>
    </div>
    <figure class="split-media reveal">
      <div class="slot {ratio_class(sl["ratio"])}">
        {picture(sl["file"], sl["alt"], 900, 1174, "(min-width: 56rem) 32vw, 92vw")}
      </div>
      <figcaption class="media-note">{e(sl["caption"])}</figcaption>
    </figure>
  </div>
</section>"""


def process(c: dict) -> str:
    p = c["process"]
    steps = ""
    for n, s in enumerate(p["steps"], 1):
        steps += f"""<li class="step reveal">
  <span class="step-n tnum" aria-hidden="true">{n}</span>
  <div class="step-body">
    <h3 class="step-title">{e(s["title"])}</h3>
    <p>{e(s["body"])}</p>
    <p class="step-tag tnum">{e(s["tag"])}</p>
  </div>
</li>"""
    mk = p.get("mark")
    mark = ""
    if mk:
        mark = f"""<div class="proc-mark reveal">
      {picture(mk["file"], mk["alt"], 320, 320, "(min-width: 62rem) 220px, 140px")}
    </div>"""
    return f"""<section class="band band-ink on-dark" id="{e(p["id"])}">
  <div class="shell proc-split">
    <div class="proc-main">
      <div class="sec-head reveal">
        <h2 class="display sec-title">{e(p["title"])}</h2>
        <p class="measure sec-lede">{e(p["lede"])}</p>
      </div>
      <div class="rail-wrap">
        <div class="rail" aria-hidden="true"><div class="rail-fill"></div></div>
        <ol class="steps">{steps}</ol>
      </div>
    </div>
    {mark}
  </div>
</section>"""


def gallery(c: dict) -> str:
    g = c["gallery"]
    # Only render a slot whose file is actually on disk. An empty frame
    # advertises what is missing; three of them make a finished section
    # look abandoned. Drop a photograph in and its slot reappears with no
    # edit to the content files.
    present = [sh for sh in g["shots"]
               if (ROOT / sh["file"].replace("../", "")).exists()]
    if not present:
        return ""
    body = "".join(f'<p class="measure sec-lede">{e(t)}</p>' for t in g.get("body", []))
    shots = ""
    for i, sh in enumerate(present):
        shots += f"""<figure class="shot reveal">
  <div class="slot {ratio_class("4 / 5")}">
    {picture(sh["file"], sh["alt"], 800, 1000, "(min-width: 46rem) 30vw, 92vw")}
  </div>
  <figcaption class="media-note">{e(sh["caption"])}</figcaption>
</figure>"""
    return f"""<section class="band band-stone gal gal-{len(present)}">
  <div class="shell gal-inner">
    <div class="gal-text reveal">
      <h2 class="display sec-title">{e(g["title"])}</h2>
      {body}
    </div>
    <div class="shots shots-{len(present)}">{shots}</div>
  </div>
</section>"""


def specs(c: dict) -> str:
    s = c["specs"]
    meta = datagrid(
        [
            {"label": s["lot_label"], "value": s["lot_value"]},
            {"label": s["campaign_label"], "value": s["campaign_value"]},
        ],
        "lot-grid",
        c["lang"],
    )
    return f"""<section class="band band-paper" id="{e(s["id"])}">
  <div class="shell">
    <div class="sec-head reveal">
      <h2 class="display sec-title">{e(s["title"])}</h2>
      <p class="measure sec-lede">{e(s["lede"])}</p>
      {meta}
    </div>
    <div class="reveal">{table(s["head"], s["rows"], s["caption"], c["lang"])}</div>
    <p class="reveal coa">
      <a class="btn btn-quiet" href="#{e(c["rfq"]["id"])}">{icon("download")}<span>{e(s["cta"])}</span></a>
    </p>
  </div>
</section>"""


def logistics(c: dict) -> str:
    l = c["logistics"]
    sl = l.get("slot")
    media = ""
    if sl:
        media = f"""<figure class="split-media reveal">
      <div class="slot {ratio_class(sl["ratio"])}">
        {picture(sl["file"], sl["alt"], 900, 1174, "(min-width: 56rem) 30vw, 92vw")}
      </div>
      <figcaption class="media-note">{e(sl["caption"])}</figcaption>
    </figure>"""
    return f"""<section class="band band-stone" id="{e(l["id"])}">
  <div class="shell">
    <div class="split logi-split">
      <div class="sec-head reveal">
        <h2 class="display sec-title">{e(l["title"])}</h2>
        <p class="measure sec-lede">{e(l["lede"])}</p>
      </div>
      {media}
    </div>
    <div class="reveal">{table(l["head"], l["rows"], "", c["lang"])}</div>
    <div class="reveal">{datagrid(l["facts"], "logi-grid", c["lang"])}</div>
  </div>
</section>"""


def certs(c: dict) -> str:
    k = c["certs"]
    items = "".join(
        f'<li class="cert reveal"><span class="cert-mark" aria-hidden="true">{icon("seal", 22)}</span>'
        f'<h3 class="cert-name">{e(i["name"])}</h3><p>{e(i["body"])}</p></li>'
        for i in k["items"]
    )
    return f"""<section class="band band-stone band-tight">
  <div class="shell">
    <h2 class="display sec-title reveal">{e(k["title"])}</h2>
    <ul class="certs">{items}</ul>
  </div>
</section>"""


def field(f: dict, lang: str) -> str:
    req = f.get("required", False)
    star = ' <span class="req" aria-hidden="true">*</span>' if req else ""
    attrs = [f'id="f-{f["name"]}"', f'name="{f["name"]}"']
    if req:
        attrs.append("required")
    for a in ("autocomplete", "inputmode"):
        if f.get(a):
            attrs.append(f'{a}="{f[a]}"')
    described = []
    if f.get("hint"):
        described.append(f'h-{f["name"]}')
    described.append(f'e-{f["name"]}')
    attrs.append(f'aria-describedby="{" ".join(described)}"')
    A = " ".join(attrs)

    if f["type"] == "select":
        opts = "".join(f'<option value="{e(o)}">{num(o, lang)}</option>' for o in f["options"])
        control = f'<select {A}><option value="">—</option>{opts}</select>'
    elif f["type"] == "textarea":
        control = f"<textarea {A} rows=\"4\"></textarea>"
    else:
        control = f'<input type="{f["type"]}" {A}>'

    hint = f'<p class="hint" id="h-{f["name"]}">{e(f["hint"])}</p>' if f.get("hint") else ""
    err = e(f.get("error", ""))
    wide = " field-wide" if f["type"] == "textarea" else ""
    return f"""<div class="field{wide}" data-field data-invalid="false">
  <label for="f-{f["name"]}">{e(f["label"])}{star}</label>
  {control}
  {hint}
  <p class="err" id="e-{f["name"]}" data-msg="{err}">{icon("alert", 16)}<span></span></p>
</div>"""


def location(c: dict) -> str:
    L = c["location"]
    f = c["footer"]
    addr_lines = [x for x in f["address"] if "TODO" not in x]
    addr = "<br>".join(e(x) for x in addr_lines)

    # Real coordinates or nothing: a pin in the wrong place sends a buyer
    # to the wrong door, which is worse than no map. With the field empty
    # the buttons search for the address instead of dropping a pin.
    gps = L.get("gps", "").strip()
    query = gps if gps else ", ".join(addr_lines)
    maps = "https://www.google.com/maps/search/?api=1&query=" + quote(query)
    waze = ("https://waze.com/ul?ll=" + quote(gps) + "&navigate=yes") if gps \
        else "https://waze.com/ul?q=" + quote(query)
    gps_value = (f'<span class="tnum" dir="ltr">{e(gps)}</span>' if gps
                 else f'<span class="pending">{e(L["gps_pending"])}</span>')

    return f"""<section class="band band-paper" id="{e(L["id"])}">
  <div class="shell split">
    <div class="split-text">
      <div class="sec-head reveal">
        <h2 class="display sec-title">{e(L["title"])}</h2>
        <p class="measure sec-lede">{e(L["lede"])}</p>
      </div>
      <dl class="datagrid loc-grid reveal">
        <div><dt>{e(L["address_label"])}</dt><dd><address class="foot-addr">{addr}</address></dd></div>
        <div><dt>{e(L["gps_label"])}</dt><dd>{gps_value}</dd></div>
      </dl>
      {datagrid(L["facts"], "loc-facts", c["lang"])}
      <p class="loc-note reveal">{e(L["note"])}</p>
    </div>
    <div class="loc-actions reveal">
      <a class="btn btn-quiet" href="{e(maps)}" target="_blank" rel="noopener">{e(L["maps"])}</a>
      <a class="btn btn-quiet" href="{e(waze)}" target="_blank" rel="noopener">{e(L["waze"])}</a>
    </div>
  </div>
</section>"""


def jsonld(c: dict) -> str:
    """Structured data for the entity, the mill and the oil.

    Two things are deliberately absent. There is no aggregateRating: Google
    forbids review markup you cannot show on the page, and inventing stars
    is the fastest way to lose rich results permanently. There are no
    offers until content/*.json carries real prices — an offer is a public
    commercial commitment, and a wrong one is quoted back at you.
    """
    f, L, P, m = c["footer"], c["location"], c["products"], c["meta"]
    S = c["schema"]
    page_url = f"{SITE_URL}/{c['path']}" if SITE_URL else "/" + c["path"]
    brand_name = c.get("brand", BRAND_DEFAULT)

    street = [x for x in f["address"][1:] if "TODO" not in x]
    postal = {
        "@type": "PostalAddress",
        "streetAddress": street[0] if street else "",
        "addressLocality": "Tlemcen",
        "postalCode": "13000",
        "addressCountry": "DZ",
    }

    org = {
        "@type": "Organization",
        "@id": page_url + "#org",
        "name": brand_name,
        "url": page_url,
        "description": m["description"],
        "email": f["email"],
        "address": postal,
        "location": {"@id": page_url + "#mill"},
    }
    if "TODO" not in f["phone"]:
        org["telephone"] = f["phone"].replace(" ", "")

    mill = {
        "@type": "Place",
        "@id": page_url + "#mill",
        "name": S["mill_name"],
        "address": postal,
    }
    gps = L.get("gps", "").strip()
    if gps:
        lat, _, lon = gps.partition(",")
        mill["geo"] = {
            "@type": "GeoCoordinates",
            "latitude": lat.strip(),
            "longitude": lon.strip(),
        }
        mill["hasMap"] = ("https://www.google.com/maps/search/?api=1&query="
                          + quote(gps))

    product = {
        "@type": "Product",
        "@id": page_url + "#oil",
        "name": S["product_name"],
        "description": P["lede"],
        "category": "Extra virgin olive oil",
        "brand": {"@type": "Brand", "name": brand_name},
        "manufacturer": {"@id": org["@id"]},
        "countryOfOrigin": {"@type": "Country", "name": "DZ"},
    }
    offers = []
    for i in P["items"]:
        price = str(i.get("price", "")).strip()
        if not price:
            continue
        offers.append({
            "@type": "Offer",
            "name": i["size"],
            "price": price,
            "priceCurrency": P.get("currency", "DZD"),
            "availability": "https://schema.org/InStock",
        })
    if offers:
        product["offers"] = offers

    graph = {"@context": "https://schema.org", "@graph": [org, mill, product]}
    payload = json.dumps(graph, ensure_ascii=False, separators=(",", ":"))
    # No "</" can reach the parser inside a script element.
    payload = payload.replace("</", "<\\/")
    return f'<script type="application/ld+json">{payload}</script>'


def wa_link(c: dict) -> str:
    """Floating WhatsApp button, or nothing while the number is a placeholder.

    A button that opens a chat with a number that does not exist costs more
    trust than it buys, so it renders only once footer.phone is real.
    """
    f = c["footer"]
    digits = re.sub(r"\D", "", f["phone"])
    if "TODO" in f["phone"] or len(digits) < 9:
        return ""
    label = f["whatsapp"]
    href = "https://wa.me/" + digits
    return (
        f'<a class="wa" href="{e(href)}" target="_blank" rel="noopener"'
        f' aria-label="{e(label)}"><span class="wa-mark">{icon("whatsapp", 22)}</span>'
        f'<span class="wa-text">{e(label)}</span></a>'
    )


def rfq(c: dict) -> str:
    r = c["rfq"]
    fields = "".join(field(f, c["lang"]) for f in r["fields"])
    return f"""<section class="band band-ink on-dark" id="{e(r["id"])}">
  <div class="shell rfq-grid">
    <div class="rfq-intro reveal">
      <h2 class="display sec-title">{e(r["title"])}</h2>
      <p class="measure sec-lede">{e(r["lede"])}</p>
      <p class="req-note">{e(r["required_note"])}</p>
    </div>
    <form class="rfq-form reveal" data-rfq novalidate
          data-endpoint="{e(r.get("endpoint", ""))}"
          data-mailto="{e(c["footer"]["email"])}">
      <div class="summary" data-summary hidden tabindex="-1" role="alert">
        <p class="summary-title">{icon("alert", 18)}<span>{e(r["error_summary_title"])}</span></p>
        <ul data-summary-list></ul>
      </div>
      <div class="fields">{fields}</div>
      <button class="btn btn-primary submit" type="submit" data-submit
              data-idle="{e(r["submit"])}" data-busy="{e(r["submitting"])}">{e(r["submit"])}</button>
      <div class="done" data-done hidden tabindex="-1">
        <p class="done-title">{icon("check", 18)}<span>{e(r["success_title"])}</span></p>
        <p>{e(r["success_body"])}</p>
      </div>
      <p class="sr-live" data-live aria-live="polite"></p>
    </form>
  </div>
</section>"""


def footer(c: dict, alts: list[dict]) -> str:
    f = c["footer"]
    addr = "<br>".join(e(l) for l in f["address"])
    langs = "".join(
        f'<li><a href="/{a["path"]}" lang="{a["lang"]}" hreflang="{a["lang"]}"'
        + (' aria-current="true"' if a["lang"] == c["lang"] else "")
        + f'>{e(a["label"])}</a></li>'
        for a in alts
    )
    return f"""<footer class="site-foot band-paper">
  <div class="shell foot-grid">
    <div>
      <p class="foot-label">{e(f["address_label"])}</p>
      <address class="foot-addr">{addr}</address>
    </div>
    <div>
      <p class="foot-label">{e(f["phone_label"])}</p>
      <p><a class="wrap-any" href="tel:{e(f["phone"].replace(" ", ""))}">{e(f["phone"])}</a></p>
      <p class="foot-label foot-label-gap">{e(f["email_label"])}</p>
      <p><a class="wrap-any" href="mailto:{e(f["email"])}">{e(f["email"])}</a></p>
    </div>
    <div>
      <p class="foot-label">{e(f["hours_label"])}</p>
      <p class="tnum">{e(f["hours"])}</p>
    </div>
    <div>
      <p class="foot-label">{e(f["lang_label"])}</p>
      <ul class="foot-langs">{langs}</ul>
    </div>
  </div>
  <div class="shell foot-legal"><p>{e(f["legal"])}</p></div>
</footer>"""

# ---------------------------------------------------------------- page

def page(c: dict, alts: list[dict]) -> str:
    assets = "assets/" if c["path"] == "" else "../assets/"
    body = "\n".join(
        [
            header(c, assets, alts),
            '<main id="main">',
            hero(c),
            variety(c),
            products(c),
            process(c),
            gallery(c),
            specs(c),
            logistics(c),
            certs(c),
            location(c),
            rfq(c),
            "</main>",
            footer(c, alts),
        ]
    )
    return f"""<!doctype html>
<html lang="{c["lang"]}" dir="{c["dir"]}" class="no-js">
<head>
{head_tag(c, assets, alts)}
<script>{JS_NOJS}</script>
{jsonld(c)}
</head>
<body>
{body}
{wa_link(c)}
<script src="{assets}js/site.js" defer></script>
</body>
</html>
"""


# ---------------------------------------------------------------- site files

def sha256_csp(src: str) -> str:
    return "'sha256-" + base64.b64encode(hashlib.sha256(src.encode()).digest()).decode() + "'"


def write_site_files(data: dict) -> None:
    """robots.txt, sitemap.xml and the two security-header files.

    The CSP hashes are computed from the same constants the pages are built
    from, so a new inline handler can never silently break the policy: change
    the handler, rebuild, and _headers follows.
    """
    paths = [c["path"] for c in data.values()]

    # -- robots.txt --------------------------------------------------------
    robots = ["User-agent: *", "Allow: /", ""]
    if SITE_URL:
        robots.append(f"Sitemap: {SITE_URL}/sitemap.xml")
    else:
        robots.append("# Sitemap: set SITE_URL and rebuild to emit sitemap.xml")
    (ROOT / "robots.txt").write_text("\n".join(robots) + "\n", "utf-8")

    # -- sitemap.xml -------------------------------------------------------
    # Absolute URLs only: a sitemap with relative locations is rejected
    # outright, so it is written only once the domain is known.
    if SITE_URL:
        urls = ""
        for path in paths:
            loc = f"{SITE_URL}/{path}"
            alts = "".join(
                f'<xhtml:link rel="alternate" hreflang="{c["lang"]}" '
                f'href="{SITE_URL}/{c["path"]}"/>' for c in data.values()
            )
            urls += (f"<url><loc>{loc}</loc>{alts}"
                     f'<xhtml:link rel="alternate" hreflang="x-default" '
                     f'href="{SITE_URL}/"/>'
                     f"<changefreq>monthly</changefreq></url>")
        (ROOT / "sitemap.xml").write_text(
            '<?xml version="1.0" encoding="UTF-8"?>'
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" '
            'xmlns:xhtml="http://www.w3.org/1999/xhtml">'
            f"{urls}</urlset>\n", "utf-8")

    # -- Content-Security-Policy -------------------------------------------
    # If the quotation form posts to a third party (Formspree, EmailJS…),
    # that origin has to be allowed or the browser blocks the submission and
    # the buyer sees a silent failure. Derived, never hand-maintained.
    endpoints = {c["rfq"].get("endpoint", "").strip() for c in data.values()}
    origins = sorted({
        f"{(u := urlsplit(url)).scheme}://{u.netloc}"
        for url in endpoints if url.startswith("http")
    })
    extra_src = (" " + " ".join(origins)) if origins else ""

    inline = sha256_csp(JS_NOJS)
    handlers = " ".join(sorted({sha256_csp(JS_FONT_SWAP), sha256_csp(JS_IMG_FALLBACK)}))
    csp = (
        "default-src 'self'; "
        f"script-src 'self' {inline} 'unsafe-hashes' {handlers}; "
        "style-src 'self' https://fonts.googleapis.com; "
        "font-src 'self' https://fonts.gstatic.com; "
        "img-src 'self' data:; "
        "media-src 'self'; "
        f"connect-src 'self'{extra_src}; "
        f"form-action 'self'{extra_src}; "
        "base-uri 'self'; "
        "object-src 'none'; "
        "frame-ancestors 'none'; "
        "upgrade-insecure-requests"
    )
    common = [
        ("Content-Security-Policy", csp),
        ("Strict-Transport-Security", "max-age=31536000; includeSubDomains"),
        ("X-Content-Type-Options", "nosniff"),
        ("Referrer-Policy", "strict-origin-when-cross-origin"),
        ("Permissions-Policy", "geolocation=(), microphone=(), camera=(), payment=(), usb=()"),
        ("Cross-Origin-Opener-Policy", "same-origin"),
    ]

    # Netlify / Cloudflare Pages
    head = "/*\n" + "".join(f"  {k}: {v}\n" for k, v in common)
    head += ("/assets/*\n  Cache-Control: public, max-age=31536000, immutable\n"
             "/*.html\n  Cache-Control: public, max-age=0, must-revalidate\n")
    (ROOT / "_headers").write_text(head, "utf-8")

    # Apache / cPanel, which is what most Algerian shared hosting runs
    ht = ["# Generated by build.py — do not edit by hand.",
          "<IfModule mod_headers.c>"]
    ht += [f'  Header always set {k} "{v}"' for k, v in common]
    ht += ["</IfModule>", "",
           "<IfModule mod_rewrite.c>",
           "  RewriteEngine On",
           "  RewriteCond %{HTTPS} !=on",
           "  RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]",
           "</IfModule>", "",
           "<IfModule mod_deflate.c>",
           "  AddOutputFilterByType DEFLATE text/html text/css application/javascript "
           "image/svg+xml application/json",
           "</IfModule>", "",
           "Options -Indexes", ""]
    (ROOT / ".htaccess").write_text("\n".join(ht), "utf-8")


def main() -> None:
    data = {l: json.loads((ROOT / "content" / f"{l}.json").read_text("utf-8")) for l in LOCALES}
    alts = [
        {"lang": d["lang"], "path": d["path"], "label": d["label"]} for d in data.values()
    ]
    for l, c in data.items():
        out = ROOT / "index.html" if c["path"] == "" else ROOT / c["path"] / "index.html"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(page(c, alts), "utf-8")
        print(f"  {out.relative_to(ROOT)}  ({len(out.read_text('utf-8')):,} bytes)")
    write_ratio_css()
    write_site_files(data)
    extra = ["robots.txt", "_headers", ".htaccess"] + (["sitemap.xml"] if SITE_URL else [])
    print("  " + ", ".join(extra))
    if not SITE_URL:
        print("  ! SITE_URL is empty: no sitemap.xml, no og:image, relative canonical.")
        print("    Once the domain exists:  SITE_URL=https://example.dz python3 build.py")


if __name__ == "__main__":
    print("TLEMCENYA — rendering pages")
    main()
